CarInsuranceQuotes-C#/CarInsuranceQuotes/Models/Quote.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsuranceQuotes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public Nullable<int> CarYear { get; set; }
        public string CarMake { get; set; }
        public string CarModel { get; set; }
        public Nullable<bool> DUI { get; set; }
        public Nullable<int> SpeedTickets { get; set; }
        public Nullable<bool> FullCoverage { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<decimal> QuoteAmount { get; set; }
    }
}

CarInsuranceQuotes-C#/CarInsuranceQuotes/Models/Quotes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

CarInsuranceQuotes-C#/CarInsuranceQuotes/Controllers/FinalController.cs
using CarInsuranceQuotes.Models;
using CarInsuranceQuotes.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarInsuranceQuotes.Controllers
{
    public class FinalController : Controller
    {
        [HttpPost]
        public ActionResult QuoteCal(QuotePar quote)
        {
            decimal qTotal = 50;
            double age = 0;
            //
            TimeSpan aget = DateTime.Now - quote.dateBirth;
            age = aget.TotalDays / 365;
            //
            if (age < 18) qTotal += 100;
            else if (age < 25 || age > 100) qTotal += 25;
            //
            if (quote.carYear < 2000) qTotal += 25;
            else if (quote.carYear > 2015) qTotal += 25;
            //
            if (quote.carMake.ToLower() == "porsche")
            {
                qTotal += 25;
                if (quote.carModel.ToLower() == "carrera") qTotal += 25;
            }
            //
            qTotal = qTotal + (quote.speedTickets * 10);
            //
            if (quote.diu == "Y") qTotal = Percent(qTotal, 25);
            //
            if (quote.cover == "1") qTotal = Percent(qTotal, 50);
            //
            quote.totalQuote = qTotal;
            //
            using (CarInsuranceQuotesEntities db = new CarInsuranceQuotesEntities())
            {
                var dbQuote = new Quote();
                dbQuote.LastName = quote.lastName;
                dbQuote.FirstName = quote.firstName;
                dbQuote.EmailAddress = quote.emailAddress;
                dbQuote.DateBirth = quote.dateBirth;
                dbQuote.CarYear = quote.carYear;
                dbQuote.CarModel = quote.carModel;
                dbQuote.CarMake = quote.carMake;
                if (quote.diu == "Y") dbQuote.DUI = true;
                else dbQuote.DUI = false;
                dbQuote.SpeedTickets = quote.speedTickets;
                if (quote.cover == "1") dbQuote.FullCoverage = true;
                else dbQuote.FullCoverage = false;
                dbQuote.QuoteDate = DateTime.Now;
                dbQuote.QuoteAmount = qTotal;
                //
                db.Quotes.Add(dbQuote);
                db.SaveChanges();
                //
            }
            //
            return View(quote);
        }
        //
        public static decimal Percent(decimal number, int percent)
        {
            number = number + ((number * percent) / 100);
            return number;
        }
        //
        
        // GET: Final
        public ActionResult Index()
        {
            return View();
        }
    }
}

CarInsuranceQuotes-C#/CarInsuranceQuotes/Controllers/HomeController.cs
using CarInsuranceQuotes.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarInsuranceQuotes.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Quote()
        {
            return View();
        }
    }
}

CarInsuranceQuotes-C#/CarInsuranceQuotes/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="img-responsive">
    <br /> 
    <p><a href="" class="btn btn-primary btn-lg"><img src="~/Content/img/car.jpg" />  </a></p>
</div>

CarInsuranceQuotes-C#/CarInsuranceQuotes/Views/Home/Quote.cshtml
<div>

    <div class="card mx-auto shadow">

        <div class="card-header text-center">
            <h3 class="alert-success text-center">You are close to get the best insurance!!</h3>
        </div>
        <br />

        <div class="card-body">

            @using (Html.BeginForm("QuoteCal", "Final", FormMethod.Post))
            {

            <div class="form-inline">
                <div class="input-group">
                    <span class="input-group-addon">First Name</span>
                    <input name="FirstName" type="text" required class="form-control mb-2 mr-sm-2" placeholder="First Name*" />
                </div>
                <div class="input-group">
                    <span class="input-group-addon">Last Name</span>
                    <input name="LastName" type="text" required class="form-control mb-2 mr-sm-2" placeholder="Last Name*" />
                </div>
                <div class="input-group">
                    <span class="input-group-addon">Birthday</span>
                    <input name="DateBirth" type="date" required class="form-control mb-2 mr-sm-2" placeholder="Birth Date*" />
                </div>
                <br /><br />

                <div class="input-group">
                    <span class="input-group-addon">Car Year</span>
                    <input name="CarYear" min="1950" max="@DateTime.Now.Year" type="number" required class="form-control mb-2 mr-sm-2" placeholder="CarYear*" />
                </div>
                <div class="input-group">
                    <span class="input-group-addon">Make</span>
                    <input name="CarMake" type="text" required class="form-control mb-2 mr-sm-2" placeholder="CarMake*" />
                </div>
                <div class="input-group">
                    <span class="input-group-addon">Model</span>
                    <input name="CarModel" type="text" required class="form-control mb-2 mr-sm-2" placeholder="CarModel*" />
                </div>

                <br /><br />

                <label for="diu1">Did you ever had a DUI?</label>
                <select required name="Diu" class="form-control" id="diu1">
                    <option selected value="">Select...</option>
                    <option value="Y">Yes</option>
                    <option value="N">No</option>
                </select>

                <br /><br />

                <label for="speed1">How many speeding tickets do you have?</label>
                <input name="SpeedTickets" type="number" required width="30" min="0" class="form-control" placeholder="*" />

                <br /><br />
                <label for="full">Please select what kind of coverage you prefer:</label>
                <select required name="Cover" class="form-control" id="full">
                    <option selected value="">Select coverage...</option>
                    <option value="1">Full coverage</option>
                    <option value="2">Just liability</option>
                </select>
                
                <br /><br />

                <label for="em1">Get your quote by email:</label>
                <input name="EmailAddress" id="em1" type="email" required class="form-control mb-2 mr-sm-2" placeholder="e-mail*" />

                <br /><br />
                <div class="col-xs-2 center-block text-center">

                    <button type="submit" class="btn btn-2 btn-block btn-primary">Submit</button>

                </div>

                <br /><br />
            </div>
             }
        </div>

    </div>

</div>